# coding: utf-8

SECURITY_URL_PREFIX = '/account'
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_PASSWORD_SALT = 'keyboardcat2'
SECURITY_EMAIL_SENDER = 'no-reply@tongdawei.cc'
#SECURITY_CONFIRMABLE = False
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
#SECURITY_TRACKABLE = False
#SECURITY_PASSWORDLESS = False
SECURITY_CHANGEABLE = True

SECURITY_CONFIRM_SALT = 'afaA<@i'
SECURITY_RESET_SALT = '03nfm@I#'
SECURITY_LOGIN_SALT = 'safa92J!@'
SECURITY_REMEMBER_SALT = 'f#34fk12t3@'



